### ISSUE TITLE
S3 access denied

### ISSUE THREAD

**Issue by YutaOkoshi** [aws-ia/cfn-ps-chainlinklabs-chainlink-node#9]
Could not retrieve VPCStack template file from S3.
![スクリーンショット 2023-10-31 16 42 00](https://github.com/aws-ia/cfn-ps-chainlinklabs-chainlink-node/assets/37532269/872da7bb-0e4a-460d-9fa6-36447cd7e9d7)

![スクリーンショット 2023-10-31 16 44 16](https://github.com/aws-ia/cfn-ps-chainlinklabs-chainlink-node/assets/37532269/69674ff3-bbf6-42fe-87f4-a02dc8be1072)

**Comment by ph0n3levr** [comment]
Seems like they broke the QSS3BucketName in this [https://github.com/aws-ia/cfn-ps-chainlinklabs-chainlink-node/pull/5](https://github.com/aws-ia/cfn-ps-chainlinklabs-chainlink-node/pull/5)

You need to change the bucketname from the new default back to aws-ia-us-east-1 and it will work again.

**Comment by YutaOkoshi** [comment]
@ph0n3levr 
Thanks for the comment.
I'm getting a different error when I try "aws-ia-us-east-1".

Error:
Parameter 'DBEngineVersion' must be one of AllowedValues

![スクリーンショット 2023-11-13 15 32 41](https://github.com/aws-ia/cfn-ps-chainlinklabs-chainlink-node/assets/37532269/439772df-7eb5-42a5-9ae7-2785138762e9)

**Comment by ph0n3levr** [comment]
Yep, this repo is all messed up. It seems like you'll need to adjust the DB Version from 11.9 to 15.2, but since the devs of this repo have hard coded the options you'll have to edit the yaml and then use that. There is a pull request pending to update this issue, but it hasn't been merged yet.

**Comment by vsnyc** [comment]
Fixed in https://github.com/aws-ia/cfn-ps-chainlinklabs-chainlink-node/pull/6

**Comment by YutaOkoshi** [comment]
thanks you guys!
